# Generated by Django 2.0.2 on 2020-06-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefun',
            new_name='imagerun',
        ),
    ]
