# Generated by Django 2.0.2 on 2020-06-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200611_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagerun',
            new_name='image',
        ),
    ]
